language: python
python:
  - "2.7"
os:
  - linux
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install -r requirements-test.txt
script: pytest
branches:
  only:
    - dev
    - master

